# Exercise 9: Which stocks move together?

In the previous exercise, you clustered companies by their daily stock price movements.  So which company have stock prices that tend to change in the same way?  Now inspect the cluster labels from your clustering to find out.

**Step 1:** Load the data _(written for you)_.

In [1]:
import pandas as pd

fn = '../datasets/company-stock-movements-2010-2015-incl.csv'
stocks_df = pd.read_csv(fn, index_col=0)

**Step 2:** Run your code from the previous exercise _(filled in for you)_.

In [4]:
companies = list(stocks_df.index)
movements = stocks_df.values

from sklearn.preprocessing import Normalizer
from sklearn.cluster import KMeans
from sklearn.pipeline import make_pipeline

normalizer = Normalizer()
kmeans = KMeans(n_clusters=14)
pipeline = make_pipeline(normalizer, kmeans)
pipe = pipeline.fit(movements)

**Step 3:** Use the `.predict()` method of the pipeline to predict the labels for `movements`.

In [5]:
labels = pipe.predict(movements)

**Step 4:** Align the cluster labels with the list of company names `companies` by creating a DataFrame `df` with `labels` and `companies` as columns.

In [7]:
a = zip(companies, labels)
df = pd.DataFrame(a, columns=['companies','labels'])

**Step 5:** Now display the DataFrame, sorted by cluster label.  To do this, use the `.sort_values()` method of `df` to sort the DataFrame by the `'labels'` column.

In [8]:
df.sort_values(by='labels')

                             companies  labels
34                          Mitsubishi       0
45                                Sony       0
21                               Honda       0
48                              Toyota       0
15                                Ford       0
7                                Canon       0
53                       Valero Energy       1
44                        Schlumberger       1
10                      ConocoPhillips       1
12                             Chevron       1
35                            Navistar       1
57                               Exxon       1
5                      Bank of America       2
16                   General Electrics       2
18                       Goldman Sachs       2
3                     American express       2
26                      JPMorgan Chase       2
1                                  AIG       2
55                         Wells Fargo       2
56                            Wal-Mart       3
54                            Walgreen       3
39                              Pfizer       3
25                   Johnson & Johnson       3
37                            Novartis       4
42                   Royal Dutch Shell       4
43                                 SAP       4
49                               Total       4
19                     GlaxoSmithKline       4
33                           Microsoft       4
52                            Unilever       4
6             British American Tobacco       4
46                      Sanofi-Aventis       4
36                    Northrop Grumman       5
4                               Boeing       5
29                     Lookheed Martin       5
59                               Yahoo       6
22                                  HP       7
14                                Dell       7
24                               Intel       8
51                   Texas instruments       8
50  Taiwan Semiconductor Manufacturing       8
38                               Pepsi       9
9                    Colgate-Palmolive       9
40                      Procter Gamble       9
41                       Philip Morris       9
28                           Coca Cola       9
27                      Kimberly-Clark       9
31                           McDonalds      10
8                          Caterpillar      10
11                               Cisco      10
13                   DuPont de Nemours      10
47                            Symantec      10
20                          Home Depot      10
32                                  3M      10
23                                 IBM      10
58                               Xerox      10
30                          MasterCard      10
0                                Apple      11
2                               Amazon      12
17                     Google/Alphabet      13

**Great job!** Using k-means, you've discovered which companies stock prices move together on the stock exchange.